### ISSUE TITLE
genlasso solution path

### ISSUE THREAD

**Issue by mhady7** [ryantibs/genlasso#4]
Hi,

Is there a way to control the number of knots (lambdas)  on the solution path  when fitting  very large datasets?...for large problems the path is tool long

Thanks
Mohamed

**Comment by ryantibs** [comment]
I'm sorry this took so long to respond to.  For large data sets, you're right, it takes a long time.  You can limit the number of steps with the `maxsteps` parameter, though this might not take you very far down the path, since the algorithm always starts at lambda = infinity.  Note that you can also restart the computation in a partially-computed saved path, but calling `genlasso()` or its various relatives on the saved path object.  Not also that you can set `approx=TRUE` and the algorithm will ignore dual boundary leaving events, which will drastically speed up the computation, but will no longer give the exact solution.  Other than that, unfortunately, there is currently no way to "skip" knots in the path algorithm, and retain the exact solution.

Finally, I should note that for very large data sets, you probably want to compute the solution over a discrete grid of lambdas (you could use a variety of convex optimization tools), rather than compute the full solution path, as the former will be much more tractable.
